# Generated by Django 5.2.8 on 2025-12-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='team',
            field=models.CharField(max_length=100),
        ),
    ]
