# Generated by Django 5.2.8 on 2025-12-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_team_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('image', models.ImageField(upload_to='tracks/')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('next', 'Next Race'), ('upcoming', 'Upcoming')], default='upcoming', max_length=20)),
            ],
        ),
    ]
