# Generated by Django 5.2.8 on 2025-12-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_race'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='location',
        ),
    ]
