# Generated by Django 5.2.8 on 2025-12-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_race_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='round_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
