# Generated by Django 5.2.8 on 2025-12-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_race_round_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('dnf', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FastetLap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('lap', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='tracks/')),
            ],
        ),
        migrations.CreateModel(
            name='Podiums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('podiums', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PolePossition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('pole', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='tracks/')),
            ],
        ),
    ]
