# Generated by Django 5.2.8 on 2025-12-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_dnf_fastetlap_podiums_polepossition'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='image',
            field=models.ImageField(default='default.png', upload_to='tracks/'),
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default='default.png', upload_to='tracks/'),
        ),
    ]
