# Generated by Django 5.2.8 on 2025-12-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_driver_image_team_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='image_team',
            field=models.ImageField(default='default.png', upload_to='tracks/'),
        ),
    ]
