# Generated by Django 5.2.8 on 2025-12-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_driver_image_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='teams/logos/')),
                ('car_image', models.ImageField(upload_to='teams/cars/')),
                ('color_class', models.CharField(max_length=50)),
            ],
        ),
    ]
