# Generated by Django 5.2.8 on 2025-12-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_aboutteams'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutteams',
            name='driver1_image',
            field=models.FileField(default='default.png', upload_to='teams/drivers/'),
        ),
        migrations.AddField(
            model_name='aboutteams',
            name='driver1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutteams',
            name='driver1_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aboutteams',
            name='driver2_image',
            field=models.FileField(default='default.png', upload_to='teams/drivers/'),
        ),
        migrations.AddField(
            model_name='aboutteams',
            name='driver2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutteams',
            name='driver2_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aboutteams',
            name='car_image',
            field=models.FileField(upload_to='teams/cars/'),
        ),
    ]
