# Generated by Django 5.2.8 on 2025-12-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_aboutteams_driver1_image_aboutteams_driver1_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team_name',
        ),
    ]
