# Generated by Django 5.2.8 on 2025-12-18 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_name_team_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_position', models.IntegerField(default=0)),
                ('prix_races', models.IntegerField(default=0)),
                ('prix_wins', models.IntegerField(default=0)),
                ('dhl', models.IntegerField(default=0)),
                ('sprint_races', models.IntegerField(default=0)),
                ('sprint_wins', models.IntegerField(default=0)),
                ('sprint_poles', models.IntegerField(default=0)),
                ('season_oints', models.IntegerField(default=0)),
                ('prix_points', models.IntegerField(default=0)),
                ('prix_podiums', models.IntegerField(default=0)),
                ('top', models.IntegerField(default=0)),
                ('dnfs', models.IntegerField(default=0)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='main.aboutteams')),
            ],
        ),
    ]
