# Generated by Django 5.2.8 on 2025-12-20 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('birthday', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('driver_number', models.IntegerField(default=0)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='drivers/')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='main.aboutteams')),
            ],
        ),
    ]
