# Generated by Django 5.2.8 on 2025-12-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_aboutdriver'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutdriver',
            name='driver_image',
            field=models.ImageField(default='default.png', upload_to='drivers/'),
        ),
    ]
