# Generated by Django 5.2.8 on 2025-12-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_aboutdriver_driver_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdriver',
            name='driver_image',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/'),
        ),
        migrations.AlterField(
            model_name='aboutdriver',
            name='image',
            field=models.ImageField(default='default_driver.png', upload_to='drivers/'),
        ),
    ]
