# Generated by Django 5.2.8 on 2025-12-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_aboutdriver_driver_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutdriver',
            name='color_class',
            field=models.CharField(default='default-bg', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutdriver',
            name='driver_image',
            field=models.FileField(blank=True, null=True, upload_to='drivers/'),
        ),
        migrations.AlterField(
            model_name='aboutdriver',
            name='image',
            field=models.FileField(default='default_driver.png', upload_to='drivers/'),
        ),
    ]
