# Generated by Django 5.2.8 on 2025-12-21 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_aboutdriver_color_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championships_current', models.IntegerField(default=0)),
                ('championships_max', models.IntegerField(default=11)),
                ('wins_current', models.IntegerField(default=0)),
                ('wins_max', models.IntegerField(default=0)),
                ('podiums_current', models.IntegerField(default=0)),
                ('podiums_max', models.IntegerField(default=0)),
                ('poles_current', models.IntegerField(default=0)),
                ('poles_max', models.IntegerField(default=0)),
                ('starts', models.IntegerField(default=0)),
                ('fastest_laps', models.IntegerField(default=0)),
                ('best_finish', models.IntegerField(default=0)),
                ('best_grid', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('retirements', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='main.aboutdriver')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_set', to='main.aboutteams')),
            ],
        ),
    ]
