# Generated by Django 5.2.8 on 2025-12-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='color_class',
            field=models.CharField(default='default-bg', max_length=50),
        ),
    ]
